# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: NodeJS CI/CD

on:
  push:
    branches: ["main"]

env:
  BRANCH_NAME: ${{ github.ref_name }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Install Netlify
        run: npm install netlify-cli@17.10.1 -g

      - run: |
          cd ./config
          touch config.env
          echo "${{ secrets.PROD }}" > config.env

      - name: Build and Testing...
        run: |
          npm run
          npm test


  deploy:
    name: Deploy
    needs: [test] #Our test must pass in order to run deploy job
    runs-on: ubuntu-latest

    steps:        
      - name: Deploy to Netlify
        id: cicd_node_netlify
        run: |
          prod_flag=""
          if [ "$BRANCH_NAME" = "main" ]; then prod_flag="--prod"; fi
          netlify deploy \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }} \
            $prod_flag 