# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: NodeJS CI/CD

on:
  push:
    branches: ["main"]


jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: |
          cd ./config
          touch config.env
          echo "${{ secrets.PROD }}" > config.env

      - name: Install Nixpacks
        run: |
          curl -sSL https://nixpacks.com/install.sh | bash
          nixpacks build . --name my-app \
                           --install-cmd "npm ci" \
                           --start-cmd "npm run start" 
        
  deploy:
    name: Deploy
    needs: [test] #Our test must pass in order to run deploy job
    runs-on: ubuntu-latest

    steps:
      - name: Install Railway
        run: npm i -g @railway/cli
          
      - name: Deploy to Railway
        # Only run this step if the branch is main
        if: github.ref == 'refs/heads/main'
        run: railway up --service ${{ secrets.RAILWAY_SERVICE }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
